### ISSUE TITLE
Unable to load numpy_formathandler accelerator from OpenGL_accelerate

### ISSUE THREAD

**Issue by thedigitalempress** [markjay4k/Audio-Spectrum-Analyzer-in-Python#1]
Hi Mark,

I came across your python audio visualizer on youtube. I decided to re-create it for my youtube channel. I'm having some trouble with loading the "numpy_formathandler accelerator from OpenGL_accelerate". When I run the code it throws back this error and I am not able to maneuver the grid like you are doing in the video. It kind of just sits there until I close out of the python shell.

![screen shot 2018-01-12 at 10 26 03 pm](https://user-images.githubusercontent.com/33044102/34902347-afb35e70-f7e7-11e7-823c-043bdd885882.png)

![screen shot 2018-01-12 at 10 26 13 pm](https://user-images.githubusercontent.com/33044102/34902348-b28c7758-f7e7-11e7-84c1-e8b43052c1bb.png)

I did some research on why this could be happening.. something about the PyOpenGL install not downloading properly. I'm still troubleshooting and researching this error but was wondering if you have any ideas as to what may be happening. I have also attached my version of the code so that you can see if I can mistyping or missing anything.

https://github.com/thedigitalempress/screenDance

Thanks!

**Comment by markjay4k** [comment]
How did you install pyOpenGL?
Did you use conda to install?

```conda install -c anaconda pyopengl```

are you using python 3.5 or 3.6?
When I did this video, I was using python3.5

**Comment by thedigitalempress** [comment]
I used the command from this site, http://pyopengl.sourceforge.net/documentation/installation.html, 
but instead I used pip3 install PyOpenGL PyOpenGL_accelerate because "pip" doesn't seem to work on my system in the terminal. 

I tried using the conda command line to install it through my terminal but that's not working either. I am also working on HighSierra on a Macbook Air. I am also using the 3.6 version of python. Do you think I should try using it with 3.5?

**Comment by thedigitalempress** [comment]
Is conda like a library manager for python?

**Comment by thedigitalempress** [comment]
I bounced back to the 3.5 version on python and now I don't get the error but I still cannot move the graph.

**Comment by thedigitalempress** [comment]
Hi Mark,

Quick update. I finally got it to work. I can now move my grid around. I had to install a specific library. I forget which one but it works!

Thanks for responding so quickly!

**Comment by markjay4k** [comment]
awesome! glad to here. whats your youtube channel?

**Comment by SyrupOnWaffles** [comment]
> Hi Mark,
> 
> Quick update. I finally got it to work. I can now move my grid around. I had to install a specific library. I forget which one but it works!
> 
> Thanks for responding so quickly!

Hey, I know this problem is long gone but if you find that project could you type _"pip list"_ so I can see what library you downloaded that fixed the problem, I'm guessing you won't respond or the file is corrupt but it would be greatly appreciated. Sorry in advance

**Comment by abatartrucks** [comment]
Hi, i can solve this problem upgrading the librarys

pip install PyOpenGL_accelerate --upgrade
pip install numpy --upgrade

and Its Done!
